### PR TITLE
Update Newtonsoft.Json to 12.0.1

### LINKED ISSUE #46: Update Newtonsoft.Json to 12.0.1

### PR DESCRIPTION
**Pull request by Varorbc**
Closes #46

### CODE REVIEW

**Comment by andreasohlund** [comment]
Thank you so much @Varorbc we're currently looking at the best timing for updating JSON.net across all our supported components. I will get back to you when we have a more firm timeline.

Are you blocked by this? Perhaps we can provide you with a prerelease build if needed?

**Comment by SzymonPobiega** [comment]
We are starting to work on this.

**Comment by Varorbc** [comment]
@andreasohlund Can you just remove the upper version constraint? JSON.net is the most ubiquitous library on NuGet and very rarely if ever has breaking changes even with major version bumps.

**Comment by timbussmann** [comment]
@Varorbc removing the upper constraint would make this package very vulnerable to breaking changes which are introduced via major versions if packages follow semantic versioning rules. This means that we can not guarantee any sort of compatibility and there are good chances that endpoints just start to break randomly because of compatibility issues.
e.g. json.net 12 has breaking changes too: https://apicomparer.particular.net/compare/Newtonsoft.Json/12.0.1...11.0.2#Set%20#1

**Comment by indualagarsamy** [comment]
@Particular/nservicebus-maintainers - can you merge this PR?

**Comment by buvinghausen** [comment]
@timbussmann yes there are technically breaking changes because some infrequently used stuff was removed.  It would be nice if Newton-King only did minor version bumps on updates but he hasn't had a minor version bump since 2012.  I will cite Microsoft's Json.NET dependencies as a pretty good case for the practice.

ASP.NET Core 2.1-3.0 depends on Newtonsoft.Json (>= 11.0.2)
ASP.NET Core 2.0 depends on Newtonsoft.Json (>= 10.0.1)
ASP.NET Core 1.x depends on Newtonsoft.Json (>= 9.0.1)

Mix in that JamesNK works with them on SignalR and I think you guys can feel fairly confident that as long as you stick with the main API footprint and aren't using the obscure items this is mostly a non-issue.   I can definitively tell you the version conflict stuff imposed on us by this library that arises every time a team member updates our dependencies is a recurring annoyance.  I'll be happy to report back any issues we encounter after updating JSON.net in the future in exchange for removing the upper bound requirements.

**Pull request merged**
